[tox]
envlist =
    py{310,311}-django52-{sync,async}
    py{312,313,314}-django{52,60}-{sync,async}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
deps =
    coverage
    django-coverage
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    -r{toxinidir}/requirements-test.txt
    -r{toxinidir}/requirements.txt

commands =
    coverage erase
    sync: coverage run -a ./runtests.py
    async: coverage run -a ./runtests.py {posargs:--async}
